<?php
/**
 * Localized Magento Editions
 *
 * @category   IntegerNet
 * @package    IntegerNet_MagentoLocalized
 * @copyright  Copyright (c) 2014 integer_net GmbH (http://www.integer-net.de/)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @author     Andreas von Studnitz <avs@integer-net.de>
 */

/** @var $this Mage_Adminhtml_Block_Template */
?>

<iframe src="<?php echo $this->getIframeUrl() ?>" width="920" height="1050" style="border: 0;"></iframe>
