<?php
/**
 * Localized Magento Editions
 *
 * @category   IntegerNet
 * @package    IntegerNet_MagentoLocalized
 * @copyright  Copyright (c) 2014 integer_net GmbH (http://www.integer-net.de/)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @author     Andreas von Studnitz <avs@integer-net.de>
 */

/** @var $this IntegerNet_MagentoLocalized_Block_News */
?>

<?php if (sizeof($this->getNewsItems())): ?>
    <?php foreach($this->getNewsItems() as $newsItem): ?>

        <div class="news-item">
            <p class="news-date"><?php echo $newsItem->getDate() ?></p>
            <h2><?php echo $newsItem->getTitle() ?></h2>
            <div class="news-description"><?php echo $newsItem->getDescription() ?></div>
            <?php if ($newsItem->getLink()): ?>
            <p class="news-link"><a href="<?php echo $newsItem->getLink() ?>"><?php echo $this->__('Read more') ?></a></p>
            <?php endif ?>
        </div>

    <?php endforeach ?>
<?php else: ?>
    <p><?php echo $this->__('News cannot be displayed at the moment. Please try again later.') ?></p>
<?php endif ?>