<?php
/**
 * Localized Magento Editions
 *
 * @category   IntegerNet
 * @package    IntegerNet_MagentoLocalized
 * @copyright  Copyright (c) 2014 integer_net GmbH (http://www.integer-net.de/)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @author     Andreas von Studnitz <avs@integer-net.de>
 */

/**
 * @see IntegerNet_MagentoLocalized_Block_Form
 * @var $this IntegerNet_MagentoLocalized_Block_Form
 */
?>

<?php $moduleTitle = $this->__(Mage::getStoreConfig('magento_localized/module_title')) ?>

<div class="content-header">
    <h3>
        <?php echo $this->__('%s Setup', $moduleTitle) ?><br />
    </h3>
</div>
<h3><?php echo $this->__('Page %s of %s', $this->getPageNumber(), $this->getNumberPages()) ?>: <?php echo $this->__('Shop Data') ?></h3>

<div class="entry-edit-head">
    <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Shop Data') ?></h4>
    <div class="form-buttons"></div>
</div>

<div class="fieldset" id="group_fields">
    <div class="hor-scroll">
        <table cellspacing="0" class="form-list">
            <tbody>
            <tr>
                <td class="label" colspan="2">
                    <p><?php echo $this->__('Please fill in your details on the company as fully as possible.') ?><br />
                    <?php echo $this->__('You may need this for the general information requirements, terms and conditions, revocation rules or some payment methods.') ?></p>
                    <p><?php echo $this->__('You can edit or complete all data at any time. You will reach this details over') ?></p>
                    <ul>
                        <li class="indent"><em><?php echo $this->__('%s &gt; Configuration', $moduleTitle) ?></em> <?php echo $this->__('or') ?></li>
                        <li class="indent"><em><?php echo $this->__('%s &gt; %s &gt; %s: %s', Mage::helper('adminhtml')->__('System'), Mage::helper('adminhtml')->__('Configuration'), Mage::helper('core')->__('General'), Mage::helper('magesetup')->__('Imprint')) ?></em></li>
                    </ul>
                </td>
                <td class="comment"></td>
            </tr>
            <?php foreach($this->getInputFields() as $field): ?>
                <tr>
                    <td class="label"><label for="field_<?php echo $field['name'] ?>"><?php echo $field['label'] ?></label></td>
                    <td class="value">
                        <?php if ($field['type'] == 'select'): ?>
                            <select name="field[<?php echo $field['name'] ?>]" id="field_<?php echo $field['name'] ?>" style="width:150px !important;">
                                <?php $value = $this->getValue($field['name']) ?>
                                <?php foreach(Mage::getSingleton($field['source_model'])->toOptionArray() as $option): ?>
                                    <option value="<?php echo $option['value'] ?>"<?php if($option['value'] == $value): ?> selected="selected"<?php endif ?>>
                                        <?php echo $option['label'] ?>
                                    </option>
                                <?php endforeach ?>
                            </select>
                        <?php elseif($field['type'] == 'textarea'): ?>
                            <textarea name="field[<?php echo $field['name'] ?>]" id="field_<?php echo $field['name'] ?>"><?php echo $this->getValue($field['name']) ?></textarea>
                        <?php else: ?>
                            <input type="text" name="field[<?php echo $field['name'] ?>]" id="field_<?php echo $field['name'] ?>"class="input-text" value="<?php echo $this->getValue($field['name']) ?>" />
                        <?php endif ?>
                    </td>
                    <td class="comment"></td>
                </tr>
            <?php endforeach ?>
            </tbody>
        </table>
    </div>
</div>

<?php if (Mage::getStoreConfig('magento_localized/display_paypal_email_field') == 1): ?>
<div class="entry-edit-head">
    <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('PayPal') ?></h4>
    <div class="form-buttons"></div>
</div>

<div class="fieldset" id="group_paypal">
    <div class="hor-scroll">
        <table cellspacing="0" class="form-list">
            <tbody>
            <tr>
                <td class="label"><label for="field_paypal_email"><?php echo $this->__('PayPal Merchant Account Email Address') ?></label></td>
                <td class="value">
                    <input type="text" name="paypal_email" id="field_paypal_email" class="input-text" value="<?php echo Mage::getStoreConfig('paypal/general/business_account') ?>" />
                </td>
                <td class="comment"></td>
            </tr>
            </tbody>
        </table>
    </div>
</div>
<?php endif ?>
