<?php
/**
 * Localized Magento Editions
 *
 * @category   IntegerNet
 * @package    IntegerNet_MagentoLocalized
 * @copyright  Copyright (c) 2014 integer_net GmbH (http://www.integer-net.de/)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @author     Andreas von Studnitz <avs@integer-net.de>
 */

/**
 * @see IntegerNet_MagentoLocalized_Block_Form
 * @var $this IntegerNet_MagentoLocalized_Block_Form
 */
?>

<?php $moduleTitle = $this->__(Mage::getStoreConfig('magento_localized/module_title')) ?>

<?php if (!$this->isInitialized() && sizeof($this->getAdditionalLanguages())): ?>

<div class="content-header">
    <h3>
        <?php echo $this->__('%s Setup', $moduleTitle) ?><br />
    </h3>
</div>
<h3><?php echo $this->__('Page %s of %s', $this->getPageNumber(), $this->getNumberPages()) ?>: <?php echo $this->__('Languages, Modules, Datatransfer') ?></h3>
<div class="entry-edit-head">
    <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Store Languages') ?></h4>
    <div class="form-buttons"></div>
</div>

<div class="fieldset" id="group_paypal">
    <div class="hor-scroll">
        <table cellspacing="0" class="form-list">
            <tbody>
            <tr>
                <td class="label"><label><?php echo $this->__('Create Additional Store Languages') ?></label></td>
                <td class="value">
                    <?php foreach($this->getAdditionalLanguages() as $languageCode => $dummy): ?>
                        <input type="checkbox" name="language[<?php echo $languageCode ?>]" id="field_language_<?php echo $languageCode ?>" class="checkbox" value="1" />
                        <label for="field_language_<?php echo $languageCode ?>"><?php echo $this->__(Mage::getStoreConfig('magento_localized/languages/' . $languageCode . '/name')) ?></label>
                        <br />
                    <?php endforeach ?>
                    (<?php echo $this->__(
                        '%s language will be created automatically.',
                        $this->__(Mage::getStoreConfig('magento_localized/languages/' . Mage::getStoreConfig('magento_localized/default_language') . '/name'))
                    ) ?>)
                </td>
                <td class="comment"></td>
            </tr>
            </tbody>
        </table>
    </div>
</div>

<?php else: ?>

<div class="content-header">
    <h3>
        <?php echo $this->__('%s Setup', $moduleTitle) ?><br />
        <?php echo $this->__('Page %s of %s', $this->getPageNumber(), $this->getNumberPages()) ?>: <?php echo $this->__('Modules, Datatransfer') ?>
    </h3>
</div>

<?php endif ?>

<div class="entry-edit-head">
    <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Integrated Modules') ?></h4>
    <div class="form-buttons"></div>
</div>

<div class="fieldset" id="group_modules">
    <div class="hor-scroll">
        <table cellspacing="0" class="form-list">
            <tbody>
            <tr id="field_modules_default">
                <td class="label"></td>
                <td class="value">
                    <?php if ($this->isInitialized()): ?>
                    <input type="radio" name="modules_default" id="field_modules_default_x" class="radio modules-default" value="" checked="checked" />
                    <label for="field_modules_default_x"><?php echo $this->__('Don\'t install additional modules') ?></label>
                    <br />
                    <?php else: ?>
                    <input type="radio" name="modules_default" id="field_modules_default_1" class="radio modules-default" value="1" checked="checked" />
                    <label for="field_modules_default_1"><?php echo $this->__('Install default modules') ?></label>
                    <br />
                    <?php endif ?>
                    <input type="radio" name="modules_default" id="field_modules_default_0" class="radio modules-default" value="0" />
                    <label for="field_modules_default_0"><?php echo $this->__('Choose which modules you want to install (Advanced Mode)') ?></label>
                </td>
            </tr>
            <tr id="field_modules" style="display: none;">
                <td class="label"><label><?php echo $this->__('Install the following modules:') ?></label></td>
                <td class="value">
                    <?php foreach ($this->getModulesData() as $moduleIdentifier => $module): ?>
                        <?php if (!isset($module['is_available']) || !$module['is_available']): continue; endif ?>
                        <input
                            type="checkbox"
                            name="module[<?php echo $moduleIdentifier ?>]"
                            id="field_module_<?php echo $moduleIdentifier ?>"
                            class="checkbox"
                            value="1"
                            <?php if ((!$this->isInitialized() && $module['is_default']) || $this->isModuleInstalled($module['code'])): ?>checked="checked"<?php endif ?>
                            <?php if ($module['is_required'] || $this->isModuleInstalled($module['code'])): ?>disabled="disabled"<?php endif ?>
                            />
                        <label for="field_module_<?php echo $moduleIdentifier ?>">
                            <?php echo $this->__($module['name']) ?>
                        </label>
                        <?php if ($module['description'] || $module['url']): ?>
                            <?php if ($module['url']): ?>
                                <a href="<?php echo $module['url'] ?>" target="_blank">
                            <?php endif ?>
                            <img src="<?php echo $this->getSkinUrl('images/i_question-mark.png') ?>"
                                 alt="<?php echo $this->escapeHtml($this->__($module['description'])) ?>"
                                 title="<?php echo $this->escapeHtml($this->__($module['description'])) ?> (<?php echo $this->__('Click for more information in a new window') ?>)" />
                            <?php if ($module['url']): ?>
                                </a>
                            <?php endif ?>
                        <?php endif ?>
                        <br />

                    <?php endforeach ?>
                </td>
                <td class="comment"></td>
            </tr>
            </tbody>
        </table>
    </div>
</div>


<div class="entry-edit-head">
    <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Help to improve %s - data transfer', $moduleTitle) ?></h4>
    <div class="form-buttons"></div>
</div>

<div class="fieldset" id="group_datatransfer">
    <div class="hor-scroll">
        <table cellspacing="0" class="form-list">
            <tbody>
            <tr>
                <td colspan="2">
                    <p><?php echo $this->__('The Localized Magento Editions (LME) are a project by the Community for the Community. The editions were created to make the start into Magento as simple as possible. The project was initiated by the Netresearch App Factory. With integer_net there are experienced and dedicated developers for the lead of implementationin the team, who have integrated the most important and best exensions together with the Community.', $moduleTitle, $moduleTitle) ?></p>
                    <p><?php echo $this->__('To track the distribution of the Localized Magento Editions, the system transmits requests with an identifier of the partner, through whom you purchased the system. You can find the responsible file under %s. It will not involve the collection of any user-related data.', 'app/code/community/IntegerNet/MagentoLocalized/Block/Tracking.php') ?></p>
                    <p><?php echo $this->__('With your consent, the transmission of usage and contact information by the Edition you can help developers and community partners actively to track the distribution of the Localized Magento Editions to develop the installation furhter and to continually improve it. Thus you and other merchants benefit from a current and attractive system and from the regular adjustments.') ?></p>
                    <p><?php echo $this->__('Of course, you can decide yourself which amount of data for transmission you want to allow to be sent how much you want to support the further developement. The project is generally only interested in information about the use of the installation and if necessary in contact details from your official imprint. There will not be any further collection of data.') ?></p>
                    <p><?php echo $this->__('Thanks in advance for your help.') ?></p>
                </td>
            </tr>
            <tr>
                <td class="value">
                    <input
                        type="radio"
                        name="field[admin__magento_localized__datatransfer]"
                        id="field_datatransfer_basic"
                        value="<?php echo IntegerNet_MagentoLocalized_Model_Source_Datatransfer::DATATRANSFER_BASIC ?>"
                        <?php if(Mage::getStoreConfig('admin/magento_localized/datatransfer') == IntegerNet_MagentoLocalized_Model_Source_Datatransfer::DATATRANSFER_BASIC): ?>checked="checked"<?php endif ?>
                        />
                </td>
                <td class="value">
                    <label for="field_datatransfer_basic"><?php echo $this->__('I don\'t want any further transfer of data.') ?></label>
                </td>
                <td class="comment"></td>
            </tr>
            <tr>
                <td class="value">
                    <input
                        type="radio"
                        name="field[admin__magento_localized__datatransfer]"
                        id="field_datatransfer_advanced"
                        value="<?php echo IntegerNet_MagentoLocalized_Model_Source_Datatransfer::DATATRANSFER_ADVANCED ?>"
                        <?php if(Mage::getStoreConfig('admin/magento_localized/datatransfer') == IntegerNet_MagentoLocalized_Model_Source_Datatransfer::DATATRANSFER_ADVANCED): ?>checked="checked"<?php endif ?>
                        />
                </td>
                <td class="value">
                    <label for="field_datatransfer_advanced"><?php echo $this->__('I help to observe the distribution of the Localized Magento Editions and want to benefit from the exclusive offerings of NR App Factory & your partners.') ?></label><br />
                    <p><?php echo $this->__('I hereby agree that contact information are transmitted to verify the reach of the Localized Magento Editions and actively support the project.') ?></p>
                    <p id="datatransfer_advanced_information_link"><a style="cursor: pointer;" onclick="$('datatransfer_advanced_information_list').show(); $('datatransfer_advanced_information_link').hide();"><?php echo $this->__('See data of the transmission') ?></a></p>
                    <ul style="list-style: disc outside; margin-left: 30px; display: none;" id="datatransfer_advanced_information_list">
                        <li><?php echo $this->__('Server IP') ?></li>
                        <li><?php echo $this->__('Transfer date') ?></li>
                        <li><?php echo $this->__('Magento version') ?></li>
                        <li><?php echo $this->__('Contact information: Store name, company, address, postal code, city, country, telephone, fax, email, website, CEO, owner') ?></li>
                    </ul><br/>
                </td>
                <td class="comment"></td>
            </tr>
            <tr>
                <td colspan="3">
                    <p><?php echo $this->__('For more information about privacy, click <a href="%s" target="_blank">here</a>.', $this->getPrivacyLinkUrl()) ?></p>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
</div>
