<?php
/**
 * Localized Magento Editions
 *
 * @category   IntegerNet
 * @package    IntegerNet_MagentoLocalized
 * @copyright  Copyright (c) 2014 integer_net GmbH (http://www.integer-net.de/)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @author     Andreas von Studnitz <avs@integer-net.de>
 */

/** @var $this IntegerNet_MagentoLocalized_Block_Dashboard_Widget */
?>

<?php if ($this->displayWidget()): ?>
<iframe src="<?php echo $this->getIframeUrl() ?>" height="299" width="100%" style="border: 0; margin-bottom: 11px;"></iframe>
<?php endif ?>
