<?php
/**
 * Localized Magento Editions
 *
 * @category   IntegerNet
 * @package    IntegerNet_MagentoLocalized
 * @copyright  Copyright (c) 2014 integer_net GmbH (http://www.integer-net.de/)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @author     Andreas von Studnitz <avs@integer-net.de>
 */

/**
 * Install mysql database configuration template
 *
 * @see Mage_Install_Block_Config
 * @var $this Mage_Install_Block_Config
 */
?>
<li>
    <div class="input-box">
        <label for="host"><?php echo $this->__('Database host') ?> <span class="required">*</span></label><br />
        <input type="text" name="connection[<?php echo $this->getIdPrefix()?>][db_host]" id="host" value="<?php echo $this->getFormData()->getDbHost() ?>" title="<?php echo $this->__('Database host') ?>" class="required-entry input-text" />
        <p style="margin-top:4px; line-height:1.3em; color:#666;">
            <small><?php echo $this->__('You can specify server port, ex.: localhost:3307<br />If you are not using default UNIX socket, you can specify it here instead of host, ex.: /var/run/mysqld/mysqld.sock') ?></small>
        </p>
    </div>
    <div class="input-box">
        <label for="dbname"><?php echo $this->__('Database Name') ?> <span class="required">*</span></label><br />
        <input type="text" name="connection[<?php echo $this->getIdPrefix()?>][db_name]" id="dbname" value="<?php echo $this->getFormData()->getDbName() ?>" title="<?php echo $this->__('Database Name') ?>" class="required-entry input-text" />
    </div>
</li>
<li>
    <div class="input-box">
        <label for="user"><?php echo $this->__('Database user name') ?> <span class="required">*</span></label><br />
        <input type="text" name="connection[<?php echo $this->getIdPrefix()?>][db_user]" id="user" value="<?php echo $this->getFormData()->getDbUser() ?>" title="<?php echo $this->__('Database user name') ?>" class="required-entry input-text" />
    </div>
    <div class="input-box">
        <label for="password"><?php echo $this->__('Database user password') ?></label><br />
        <input type="password" name="connection[<?php echo $this->getIdPrefix()?>][db_pass]" id="password" value="" title="<?php echo $this->__('Database user password') ?>" class="input-text" />
    </div>
</li>
<li>
    <div class="input-box">
        <label for="prefix"><?php echo $this->__('Tables Prefix') ?></label><br />
        <input type="text" name="connection[<?php echo $this->getIdPrefix()?>][db_prefix]" id="prefix" value="<?php echo $this->getFormData()->getDbPrefix() ?>" title="<?php echo $this->__('Tables Prefix') ?>" class="validate-data input-text" />
        <p style="margin-top:4px; line-height:1.3em; color:#666;">
            <small><?php echo $this->__('(Optional. Leave blank for no prefix)') ?></small>
        </p>
    </div>
</li>
