<?php
/**
 * Localized Magento Editions
 *
 * @category   IntegerNet
 * @package    IntegerNet_MagentoLocalized
 * @copyright  Copyright (c) 2013 integer_net GmbH (http://www.integer-net.de/)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @author     Andreas von Studnitz <avs@integer-net.de>
 */

/** @var $this IntegerNet_MagentoLocalized_Block_Logo */
?>

<?php if ($this->isActive()): ?>

<a href="<?php echo $this->getLinkUrl() ?>" target="_blank" style="display: block; float: left; width: 253px; height: 53px; overflow: hidden;">
    <img class="logo" src="<?php echo $this->getLogoUrl() ?>" alt="<?php echo $this->getLogoAlt() ?>" />';
</a>

<?php endif ?>