<?php
/**
 * Localized Magento Editions
 *
 * @category   IntegerNet
 * @package    IntegerNet_MagentoLocalized
 * @copyright  Copyright (c) 2013 integer_net GmbH (http://www.integer-net.de/)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @author     Andreas von Studnitz <avs@integer-net.de>
 */

/** @var $this IntegerNet_MagentoLocalized_Block_Logo */
?>

<?php if ($this->isActive()): ?>

<a href="<?php echo $this->getLinkUrl() ?>" target="_blank" style="display: block; float: left; width: 170px; height: 53px; overflow: hidden;">
    <img class="logo" src="<?php echo $this->getLogoUrl() ?>" alt="<?php echo $this->getLogoAlt() ?>" />';
</a>

<?php if (Mage::getStoreConfig('magento_localized/logo_2_filename')): ?>
    <a href="<?php echo Mage::getStoreConfig('magento_localized/module_url_override') ? Mage::getStoreConfig('magento_localized/module_url_override') : Mage::getStoreConfig('magento_localized/module_url') ?>" target="_blank" title="<?php echo Mage::getStoreConfig('magento_localized/module_title') . Mage::getStoreConfig('magento_localized/module_title_suffix') ?>" style="display: block; float: left; width: 253px; height: 53px; overflow: hidden;text-align: left;">
        <img class="logo" src="<?php echo $this->getSkinUrl(Mage::getStoreConfig('magento_localized/logo_2_filename')) ?>" alt="<?php echo Mage::getStoreConfig('magento_localized/module_title') . Mage::getStoreConfig('magento_localized/module_title_suffix') ?>" style="margin-left: 0; margin-top: 2px;"/>
    </a>
<?php endif ?>

<?php endif ?>